/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LuiAlert {
        "accent": boolean;
        "type": string;
    }
    interface LuiButton {
        "ghost": boolean;
        "type": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLLuiAlertElement extends Components.LuiAlert, HTMLStencilElement {
    }
    var HTMLLuiAlertElement: {
        prototype: HTMLLuiAlertElement;
        new (): HTMLLuiAlertElement;
    };
    interface HTMLLuiButtonElement extends Components.LuiButton, HTMLStencilElement {
    }
    var HTMLLuiButtonElement: {
        prototype: HTMLLuiButtonElement;
        new (): HTMLLuiButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "lui-alert": HTMLLuiAlertElement;
        "lui-button": HTMLLuiButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface LuiAlert {
        "accent"?: boolean;
        "type"?: string;
    }
    interface LuiButton {
        "ghost"?: boolean;
        "type"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "lui-alert": LuiAlert;
        "lui-button": LuiButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lui-alert": LocalJSX.LuiAlert & JSXBase.HTMLAttributes<HTMLLuiAlertElement>;
            "lui-button": LocalJSX.LuiButton & JSXBase.HTMLAttributes<HTMLLuiButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
